CREATE TABLE IF NOT EXISTS DS.FT_BALANCE_F (
	ON_DATE DATE
	ACCOUNT_RK NUMERIC
	CREDIT_AMOUNT NUMERIC(23,8)
	CREDIT_AMOUNT_RUB NUMERIC(23,8)
	DEBET_AMOUNT NUMERIC(23,8)
	DEBET_AMOUNT_RUB NUMERIC(23,8)
);