CREATE TABLE IF NOT EXISTS DS.MD_CURRENCY_D (
	CURRENCY_RK INTEGER NOT NULL,
	DATA_ACTUAL_DATE DATE NOT NULL,
	DATA_ACTUAL_END_DATE DATE,
	CURRENCY_CODE VARCHAR(3),
	CODE_ISO_CHAR VARCHAR(3),
	PRIMARY KEY (CURRENCY_RK, DATA_ACTUAL_DATE)
);